apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  PGDATA: /var/lib/postgresql/pgdata
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_test
  POSTGRES_PASSWORD: ps_passtest
