FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src /code/src

ARG POSTGRES_URI
ARG MONGODB_URI
ARG KAFKA_BROKER_SERVER
ARG OTEL_SERVICE_NAME
ARG OTEL_EXPORTER_OTLP_ENDPOINT
ARG OTEL_RESOURCE_ATTRIBUTES
ARG OTEL_TRACES_EXPORTER
ARG OTEL_EXPORTER_JAEGER_ENDPOINT
ARG SPLUNK_PROFILER_ENABLED
ARG SPLUNK_ACCESS_TOKEN

ENV POSTGRES_URI $POSTGRES_URI
ENV MONGODB_URI $MONGODB_URI
ENV KAFKA_BROKER_SERVER $KAFKA_BROKER_SERVER
ENV OTEL_SERVICE_NAME $OTEL_SERVICE_NAME
ENV OTEL_EXPORTER_OTLP_ENDPOINT $OTEL_EXPORTER_OTLP_ENDPOINT
ENV OTEL_RESOURCE_ATTRIBUTES $OTEL_RESOURCE_ATTRIBUTES
ENV SPLUNK_PROFILER_ENABLED $SPLUNK_PROFILER_ENABLED
ENV OTEL_TRACES_EXPORTER $OTEL_TRACES_EXPORTER
ENV OTEL_EXPORTER_JAEGER_ENDPOINT $OTEL_EXPORTER_JAEGER_ENDPOINT
ENV SPLUNK_PROFILER_ENABLED $SPLUNK_PROFILER_ENABLED
ENV SPLUNK_ACCESS_TOKEN $SPLUNK_ACCESS_TOKEN

# 
CMD ["splunk-py-trace", "uvicorn", "src.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
