apiVersion: v1
kind: ConfigMap
metadata:
  name: python-demo-config
  labels:
    app: mongodb
data:
  MONGODB_URI: "mongodb://mongodb_user:mongodb_pass@mongo:27017/"
  POSTGRES_URI: "postgresql://ps_test:ps_passtest@postgres:5432/ps_db"
  KAFKA_BROKER_SERVER: "kafka-broker-service:9092"
  KAFKA_TOPIC: "events"
  OTEL_SERVICE_NAME: "python-demo-app"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=testing"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  OTEL_TRACES_EXPORTER: ""
  OTEL_EXPORTER_JAEGER_ENDPOINT: ""
  SPLUNK_PROFILER_ENABLED: "true"
  SPLUNK_ACCESS_TOKEN: ""