apiVersion: v1
kind: Service
metadata:
  name: python-demo-app
spec:
  selector:
    app: python-demo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
