apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: listener-service-1
      nodePort: 30020
    - protocol: TCP
      port: 9093
      name: listener-service-2
      nodePort: 30021
    - protocol: TCP
      port: 9094
      name: listener-service-3
      nodePort: 30022
  selector:
    app: kafka-broker
